### ISSUE TITLE
[BUG] khage does not work with latest kha/kode studio

### ISSUE THREAD

**Issue by lewislepton** [wighawag/khage#1]
khage will need a update due to changes with kha and kode studio.
tried building etc, such as 'BlenderOperation' should be 'BlenderFactor'

would like to use khage, but few errors that need addressing

cheers

**Comment by lewislepton** [comment]
here is one such error from terminal to build to html

```
/usr/local/lib/haxe/lib/khage/git/Sources/khage/g4/PipelineExtension.hx:45: characters 28-68 : Enum<kha.graphics4.BlendingOperation> has no field BlendOne
/usr/local/lib/haxe/lib/khage/git/Sources/khage/g4/PipelineExtension.hx:46: characters 33-74 : Enum<kha.graphics4.BlendingOperation> has no field BlendZero

Haxe compiler error.
```

**Comment by wighawag** [comment]
Thanks for the report, these issue are now fixed. 
Note that khage is unfinished, I am waiting for a change in kha to process shader but it should be usable. let me know if there is any more problem.
